### PR TITLE
fix: Upgrade TypeDoc to v0.16

### PR DESCRIPTION
**Pull request by Gerrit0**
The public API changed.

Presumably the TypedocApp extends Application class was intended to trick TypeDoc into reading tsconfig.json / typedoc.json by default. This is no longer necessary with v0.16 so long as the readers are added.

---

I was unable to compile locally, I believe due to #87? Though that's apparently blocked on a release of TypeDoc that has happened, so I'm not sure.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/documentalist](https://github.com/palantir/documentalist), @Gerrit0! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by Gerrit0** [comment]
Okay then, I guess the handlebars definitions weren't just local... Not sure what needs to be done here.

**Comment by Gerrit0** [comment]
Looking into the tests, some of the test failures are due to TypeDoc doing the right thing now with `isExported = true` for child reflections.

One test is failing for a reason I don't understand though, excludePaths appears to not be working... I didn't change anything there.

**Comment by adidahiya** [comment]
thanks for the PR @Gerrit0! not sure what you're referring to re: excludePaths... tests seem to be passing after I updated snapshots

**Comment by Gerrit0** [comment]
Good to hear! Maybe something weird was going on with my local environment. No reflections were being excluded.

**Comment by adidahiya** [comment]
@Gerrit0 just released 2.6.0

**Pull request merged**
